import React, { useState } from 'react';
import { 
  Sparkles, 
  Bookmark, 
  ThumbsUp, 
  ThumbsDown, 
  ArrowUpRight, 
  AlertTriangle, 
  Workflow
} from 'lucide-react';
import PageHeader from '../components/PageHeader';

function formatTime(iso) {
  if (!iso) return '';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}

function recordBadge(recordType) {
  if (recordType === 'issue') return { label: 'Issue', className: 'badge badge-amber' };
  if (recordType === 'pull_request') return { label: 'PR', className: 'badge badge-blue' };
  if (recordType === 'thread' || recordType === 'email') return { label: 'Email', className: 'badge badge-purple' };
  return { label: 'Source', className: 'badge badge-gray' };
}

export default function AnswerScreen({ navigateTo, queryResult }) {
  const [feedback, setFeedback] = useState(null);
  const [followUp, setFollowUp] = useState('');

  if (!queryResult) {
    return (
      <div>
        <PageHeader 
          breadcrumb={['Workspace', 'Ask KnowledgeOps', 'Answer']}
          title="AI Answer + Evidence"
          subtitle="Every answer is generated by the agent pipeline and linked to source records."
          actions={
            <button onClick={() => navigateTo('ask')} className="btn btn-primary">
              <Sparkles size={15} />
              <span>Ask KnowledgeOps</span>
            </button>
          }
        />
        <div className="card" style={{ padding: '24px', textAlign: 'center', color: '#64748B' }}>
          <div style={{ fontWeight: 700, color: '#0F172A', marginBottom: '6px' }}>No answer yet</div>
          <div style={{ fontSize: '0.8rem', marginBottom: '14px' }}>
            Ask a question in Ask KnowledgeOps to run the Planner → Retrieval → Analysis → LLM → Workflow → Evidence pipeline.
          </div>
          <button className="btn btn-primary" onClick={() => navigateTo('ask')}>
            <Sparkles size={15} />
            <span>Ask KnowledgeOps</span>
          </button>
        </div>
      </div>
    );
  }

  const evidence = queryResult.evidence || [];
  const risks = queryResult.risks || [];
  const blockers = queryResult.blockers || [];
  const decisions = queryResult.decisions || [];
  const actionDetails = queryResult.action_details && queryResult.action_details.length > 0
    ? queryResult.action_details
    : (queryResult.recommended_actions || []).map((action, index) => ({
        action, priority: index + 1, owner: '', depends_on: [], evidence_source_ids: []
      }));
  const trace = queryResult.trace || [];
  const answerTime = trace.length > 0 ? formatTime(trace[0].started_at) : formatTime(new Date().toISOString());
  const totalMs = trace.reduce((sum, stage) => sum + (stage.duration_ms || 0), 0);
  const sourceCount = new Set(evidence.map((item) => item.source)).size;
  const atRisk = (queryResult.status || '').toLowerCase() === 'at risk';

  const citationsFor = (text) => {
    const lower = (text || '').toLowerCase();
    return evidence
      .filter((item) => {
        if (item.source_id && lower.includes(item.source_id.toLowerCase())) return true;
        const tokens = (item.claim || '').toLowerCase().split(/\W+/).filter((t) => t.length > 4);
        const matches = tokens.filter((token) => lower.includes(token)).length;
        return tokens.length > 0 && matches >= 2;
      })
      .map((item) => `[${item.citation_id}]`);
  };

  const citationLabel = (sourceId) => {
    const item = evidence.find((e) => e.source_id === sourceId || e.source_id.includes(sourceId) || sourceId.includes(e.source_id));
    return item ? `[${item.citation_id}]` : '';
  };

  const headline = atRisk
    ? `The ${queryResult.project} ${queryResult.target_release || ''} release is at risk`.replace(/\s+/g, ' ')
    : (queryResult.answer || '').split('. ')[0];

  const insightCards = [
    ...blockers.map((text) => ({ badge: 'Blocker', badgeClass: 'badge badge-red', border: '#EF4444', title: text, text })),
    ...risks.map((text) => ({ badge: 'Risk', badgeClass: 'badge badge-amber', border: '#F59E0B', title: text, text })),
    ...decisions.map((text) => ({ badge: 'Decision', badgeClass: 'badge badge-purple', border: '#7C3AED', title: text, text }))
  ];

  return (
    <div>
      <PageHeader 
        breadcrumb={['Workspace', 'Ask KnowledgeOps', 'Answer']}
        title="AI Answer + Evidence"
        subtitle={`${queryResult.project || 'Workspace'} · ${queryResult.target_release ? `${queryResult.target_release} · ` : ''}GitHub + Gmail`}
        actions={
          <div style={{ display: 'flex', gap: '10px' }}>
            <button className="btn btn-secondary">
              <Bookmark size={15} />
              <span>Save answer</span>
            </button>
            <button 
              onClick={() => navigateTo('ask')}
              className="btn btn-primary"
            >
              <Sparkles size={15} />
              <span>Ask KnowledgeOps</span>
            </button>
          </div>
        }
      />

      {/* User Query Prompt Box */}
      <div style={{
        padding: '14px 18px',
        background: '#F1F5F9',
        border: '1px solid #E2E8F0',
        borderRadius: '8px',
        marginBottom: '24px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <span className="badge badge-purple" style={{ fontSize: '0.7rem' }}>You</span>
          <span style={{ fontWeight: 600, fontSize: '0.9rem', color: '#0F172A' }}>
            {queryResult.question}
          </span>
        </div>
        <span style={{ fontSize: '0.75rem', color: '#94A3B8' }}>{answerTime}</span>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 360px', gap: '24px' }}>
        {/* Left Column: AI Answer Content */}
        <div>
          <div className="card" style={{ marginBottom: '24px' }}>
            {/* Header */}
            <div style={{ marginBottom: '16px' }}>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0F172A', marginBottom: '4px' }}>
                {headline}
              </h2>
              <div style={{ fontSize: '0.75rem', color: '#64748B' }}>
                Generated by KnowledgeOps agents · {answerTime} · Run {queryResult.run_id} · Evidence checked
              </div>
            </div>

            {/* Badges */}
            <div style={{ display: 'flex', gap: '8px', marginBottom: '16px', flexWrap: 'wrap' }}>
              <span className={`badge ${atRisk ? 'badge-red' : 'badge-green'}`}>{queryResult.status || 'Answered'}</span>
              <span className="badge badge-blue">{queryResult.confidence || 'medium'} confidence</span>
              <span className="badge badge-gray">{evidence.length} cited records · {sourceCount} sources</span>
            </div>

            {/* Core Answer Text */}
            <p style={{ fontSize: '0.875rem', color: '#334155', lineHeight: 1.6, marginBottom: '20px' }}>
              {queryResult.answer}{' '}
              <span style={{ color: '#2563EB', fontWeight: 600 }}>
                {evidence.map((item) => `[${item.citation_id}]`).join(' ')}
              </span>
            </p>

            {/* Subsection: What the evidence tells us */}
            <div style={{ marginBottom: '20px' }}>
              <h4 style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0F172A', marginBottom: '12px' }}>
                What the evidence tells us
              </h4>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '0.825rem' }}>
                {insightCards.length > 0 ? insightCards.map((card, index) => (
                  <div key={index} style={{ padding: '10px 14px', background: '#F8FAFC', borderRadius: '6px', borderLeft: `3px solid ${card.border}` }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                      <span className={card.badgeClass} style={{ fontSize: '0.65rem' }}>{card.badge}</span>
                      <strong style={{ color: '#0F172A' }}>{card.title}</strong>
                    </div>
                    <div style={{ color: '#475569', fontSize: '0.775rem' }}>
                      {card.text}{' '}
                      <span style={{ color: '#2563EB', fontWeight: 600 }}>{citationsFor(card.text).join(' ')}</span>
                    </div>
                  </div>
                )) : (
                  <div style={{ padding: '10px 14px', background: '#F8FAFC', borderRadius: '6px', color: '#475569' }}>
                    No risks, blockers, or decisions were identified in the retrieved records.
                  </div>
                )}
              </div>
            </div>

            {/* Alert Box */}
            <div className="alert-box alert-amber" style={{ marginBottom: '20px' }}>
              <AlertTriangle size={18} color="#D97706" style={{ flexShrink: 0 }} />
              <div>
                <strong style={{ display: 'block', marginBottom: '2px' }}>At risk is not the same as confirmed delay</strong>
                The available evidence supports an at-risk assessment. It does not establish that the release will definitely be delayed.
              </div>
            </div>

            {/* Subsection: Recommended next steps */}
            <div style={{ marginBottom: '24px' }}>
              <h4 style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0F172A', marginBottom: '12px' }}>
                Recommended next steps
              </h4>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '0.8rem' }}>
                {actionDetails.length > 0 ? actionDetails.map((item, index) => (
                  <div key={index} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', padding: '10px', background: '#F8FAFC', borderRadius: '6px' }}>
                    <span style={{ width: '20px', height: '20px', borderRadius: '50%', background: '#2563EB', color: '#FFFFFF', fontWeight: 700, fontSize: '0.7rem', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>{item.priority || index + 1}</span>
                    <div>
                      <strong style={{ color: '#0F172A' }}>{item.action}</strong>
                      <div style={{ color: '#64748B', fontSize: '0.725rem', marginTop: '2px' }}>
                        {item.owner ? `${item.owner} · ` : ''}
                        Draft only — not executed
                        {item.depends_on && item.depends_on.length > 0 ? ` · Depends on: ${item.depends_on.join(', ')}` : ''}
                        {' '}
                        <span style={{ color: '#2563EB' }}>
                          {(item.evidence_source_ids || []).map((id) => citationLabel(id)).filter(Boolean).join(' ')}
                        </span>
                      </div>
                    </div>
                  </div>
                )) : (
                  <div style={{ padding: '10px 14px', background: '#F8FAFC', borderRadius: '6px', color: '#475569' }}>
                    No recommended actions were drafted for this answer.
                  </div>
                )}
              </div>
            </div>

            {/* Bottom Feedback & Workflow Action Bar */}
            <div style={{
              paddingTop: '16px',
              borderTop: '1px solid #F1F5F9',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '0.75rem', color: '#64748B' }}>
                <span>Was this answer useful?</span>
                <button 
                  onClick={() => setFeedback('up')} 
                  style={{ background: feedback === 'up' ? '#EFF6FF' : 'transparent', border: '1px solid #CBD5E1', borderRadius: '4px', padding: '4px 8px', cursor: 'pointer' }}
                >
                  <ThumbsUp size={13} color={feedback === 'up' ? '#2563EB' : '#64748B'} />
                </button>
                <button 
                  onClick={() => setFeedback('down')} 
                  style={{ background: feedback === 'down' ? '#FEF2F2' : 'transparent', border: '1px solid #CBD5E1', borderRadius: '4px', padding: '4px 8px', cursor: 'pointer' }}
                >
                  <ThumbsDown size={13} color={feedback === 'down' ? '#EF4444' : '#64748B'} />
                </button>
              </div>

              <button 
                onClick={() => navigateTo('workflows')}
                className="btn btn-secondary btn-sm"
              >
                <Workflow size={14} />
                <span>View agent run</span>
              </button>
            </div>
          </div>

          {/* Follow-up Query Composer Box */}
          <div className="card" style={{ padding: '14px' }}>
            <div style={{ display: 'flex', gap: '10px' }}>
              <input 
                type="text" 
                className="input" 
                placeholder="Ask a follow-up about this release..."
                value={followUp}
                onChange={(e) => setFollowUp(e.target.value)}
              />
              <button 
                className="btn btn-primary" 
                style={{ flexShrink: 0 }}
                onClick={() => navigateTo('ask')}
              >
                <span>↑ Ask KnowledgeOps</span>
              </button>
            </div>
          </div>
        </div>

        {/* Right Column: Evidence & Provenance */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {/* Card 1: Evidence behind this answer */}
          <div className="card">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
              <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#0F172A' }}>Evidence behind this answer</h4>
              <span 
                onClick={() => navigateTo('evidence')}
                style={{ fontSize: '0.725rem', color: '#2563EB', fontWeight: 600, cursor: 'pointer' }}
              >
                Explore all →
              </span>
            </div>
            <div style={{ fontSize: '0.725rem', color: '#64748B', marginBottom: '14px' }}>
              Select a citation to inspect the original source.
            </div>

            {evidence.length > 0 ? evidence.map((item, index) => {
              const badge = recordBadge(item.record_type);
              return (
                <div key={item.citation_id} style={{ padding: '10px', background: '#F8FAFC', borderRadius: '6px', border: '1px solid #E2E8F0', marginBottom: index < evidence.length - 1 ? '10px' : 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
                    <span style={{ fontWeight: 700, color: '#2563EB', fontSize: '0.8rem' }}>[{item.citation_id}]</span>
                    <span className={badge.className} style={{ fontSize: '0.65rem' }}>{badge.label}</span>
                  </div>
                  <div style={{ fontWeight: 700, fontSize: '0.8rem', color: '#0F172A', marginBottom: '2px' }}>
                    {item.title}
                  </div>
                  <p style={{ fontSize: '0.725rem', color: '#475569', fontStyle: 'italic', marginBottom: '6px' }}>
                    "{item.relevant_information}"
                  </p>
                  <div style={{ fontSize: '0.675rem', color: '#64748B', display: 'flex', justifyContent: 'space-between' }}>
                    <span>{item.source} · {item.source_id}</span>
                    <span>{item.author}</span>
                  </div>
                  <div 
                    onClick={() => navigateTo('evidence')}
                    style={{ fontSize: '0.675rem', color: '#2563EB', fontWeight: 600, marginTop: '4px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '2px' }}
                  >
                    Open original source <ArrowUpRight size={10} />
                  </div>
                </div>
              );
            }) : (
              <div style={{ fontSize: '0.775rem', color: '#64748B' }}>No evidence records were attached to this answer.</div>
            )}
          </div>

          {/* Card 2: Answer provenance */}
          <div className="card">
            <h4 style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0F172A', marginBottom: '12px' }}>
              Answer provenance
            </h4>

            <div style={{ fontSize: '0.75rem', color: '#475569', display: 'flex', flexDirection: 'column', gap: '6px', marginBottom: '12px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span>Run:</span>
                <strong>{queryResult.run_id}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span>Retrieval:</span>
                <strong>{[...new Set(evidence.map((e) => e.source))].join(' + ') || '—'}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span>Started:</span>
                <strong>{trace.length > 0 && trace[0].started_at ? new Date(trace[0].started_at).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—'}</strong>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span>Execution:</span>
                <strong style={{ color: '#059669' }}>{totalMs >= 1000 ? `${(totalMs / 1000).toFixed(1)} seconds` : `${Math.round(totalMs)} ms`}</strong>
              </div>
            </div>

            <div style={{ fontSize: '0.675rem', color: '#64748B', background: '#F8FAFC', padding: '8px', borderRadius: '4px', marginBottom: '10px' }}>
              {trace.length > 0 ? trace.map((stage) => stage.agent.replace(' Agent', '')).join(' → ') : 'Planner → Retrieval → Analysis → LLM → Workflow → Evidence'}
            </div>

            <div 
              onClick={() => navigateTo('workflows')}
              style={{ fontSize: '0.75rem', color: '#2563EB', fontWeight: 600, cursor: 'pointer' }}
            >
              View agent trace →
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
